/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cad_gfsilva' at '8/5/16 4:51 PM' with Gradle 2.11
 *
 * @author cad_gfsilva, @date 8/5/16 4:51 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
